/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        phone: string;
                        name: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                phone: string | null;
                                name: string;
                                verifiedAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                            devOtp?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        phone: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            devOtp?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        phone: string;
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                phone: string | null;
                                name: string;
                                verifiedAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        phone: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                phone: string | null;
                                name: string;
                                verifiedAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                phone: string | null;
                                name: string;
                                verifiedAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                phone: string | null;
                                name: string;
                                verifiedAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                phone: string | null;
                                name: string;
                                verifiedAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/market/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            phase: "pre_open" | "open" | "post_close" | "closed_weekend" | "closed_holiday";
                            /** Format: date-time */
                            at: string;
                            nextOpenAt: string | null;
                            lastCloseAt: string | null;
                            holidayName: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results: {
                                symbol: string;
                                name: string;
                                /** @enum {string} */
                                exchange: "NSE" | "BSE";
                                sector: string | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/stocks/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    exchange?: "nse" | "both";
                };
                header?: never;
                path: {
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            instrument: {
                                symbol: string;
                                name: string;
                                /** @enum {string} */
                                exchange: "NSE" | "BSE";
                                sector: string | null;
                            };
                            quote: {
                                symbol: string;
                                price: number;
                                previousClose: number;
                                open: number | null;
                                dayHigh: number | null;
                                dayLow: number | null;
                                volume: number | null;
                                averageVolume: number | null;
                                change: number;
                                changePct: number;
                                fiftyTwoWeekHigh: number | null;
                                fiftyTwoWeekLow: number | null;
                                freshness: {
                                    /** Format: date-time */
                                    asOf: string;
                                    delayedMinutes: number;
                                    stale: boolean;
                                    source: string;
                                };
                            };
                            events: {
                                nextResultsAt: string | null;
                                lastResultsAt: string | null;
                                exDividendAt: string | null;
                            };
                            bseQuote: {
                                symbol: string;
                                price: number;
                                previousClose: number;
                                open: number | null;
                                dayHigh: number | null;
                                dayLow: number | null;
                                volume: number | null;
                                averageVolume: number | null;
                                change: number;
                                changePct: number;
                                fiftyTwoWeekHigh: number | null;
                                fiftyTwoWeekLow: number | null;
                                freshness: {
                                    /** Format: date-time */
                                    asOf: string;
                                    delayedMinutes: number;
                                    stale: boolean;
                                    source: string;
                                };
                            } | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/stocks/{symbol}/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    range?: "1M" | "3M" | "6M" | "1Y";
                };
                header?: never;
                path: {
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            symbol: string;
                            /** @enum {string} */
                            range: "1M" | "3M" | "6M" | "1Y";
                            candles: {
                                /** Format: date-time */
                                t: string;
                                o: number;
                                h: number;
                                l: number;
                                c: number;
                                v: number | null;
                            }[];
                            freshness: {
                                /** Format: date-time */
                                asOf: string;
                                delayedMinutes: number;
                                stale: boolean;
                                source: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            watchlists: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                position: number;
                                items: {
                                    /** Format: uuid */
                                    id: string;
                                    symbol: string;
                                    instrument: {
                                        symbol: string;
                                        name: string;
                                        /** @enum {string} */
                                        exchange: "NSE" | "BSE";
                                        sector: string | null;
                                    };
                                    thesis: ({
                                        /** @enum {string} */
                                        kind: "target_price";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "breakout_above";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "through_results";
                                    } | {
                                        /** @enum {string} */
                                        kind: "curious";
                                    }) | null;
                                    /** Format: date-time */
                                    addedAt: string;
                                    addedPrice: number | null;
                                    quote: {
                                        symbol: string;
                                        price: number;
                                        previousClose: number;
                                        open: number | null;
                                        dayHigh: number | null;
                                        dayLow: number | null;
                                        volume: number | null;
                                        averageVolume: number | null;
                                        change: number;
                                        changePct: number;
                                        fiftyTwoWeekHigh: number | null;
                                        fiftyTwoWeekLow: number | null;
                                        freshness: {
                                            /** Format: date-time */
                                            asOf: string;
                                            delayedMinutes: number;
                                            stale: boolean;
                                            source: string;
                                        };
                                    } | null;
                                    sparkline: number[];
                                }[];
                                lastSeenAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            watchlist: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                position: number;
                                items: {
                                    /** Format: uuid */
                                    id: string;
                                    symbol: string;
                                    instrument: {
                                        symbol: string;
                                        name: string;
                                        /** @enum {string} */
                                        exchange: "NSE" | "BSE";
                                        sector: string | null;
                                    };
                                    thesis: ({
                                        /** @enum {string} */
                                        kind: "target_price";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "breakout_above";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "through_results";
                                    } | {
                                        /** @enum {string} */
                                        kind: "curious";
                                    }) | null;
                                    /** Format: date-time */
                                    addedAt: string;
                                    addedPrice: number | null;
                                    quote: {
                                        symbol: string;
                                        price: number;
                                        previousClose: number;
                                        open: number | null;
                                        dayHigh: number | null;
                                        dayLow: number | null;
                                        volume: number | null;
                                        averageVolume: number | null;
                                        change: number;
                                        changePct: number;
                                        fiftyTwoWeekHigh: number | null;
                                        fiftyTwoWeekLow: number | null;
                                        freshness: {
                                            /** Format: date-time */
                                            asOf: string;
                                            delayedMinutes: number;
                                            stale: boolean;
                                            source: string;
                                        };
                                    } | null;
                                    sparkline: number[];
                                }[];
                                lastSeenAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlists/{watchlistId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    watchlistId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            watchlist: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                position: number;
                                items: {
                                    /** Format: uuid */
                                    id: string;
                                    symbol: string;
                                    instrument: {
                                        symbol: string;
                                        name: string;
                                        /** @enum {string} */
                                        exchange: "NSE" | "BSE";
                                        sector: string | null;
                                    };
                                    thesis: ({
                                        /** @enum {string} */
                                        kind: "target_price";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "breakout_above";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "through_results";
                                    } | {
                                        /** @enum {string} */
                                        kind: "curious";
                                    }) | null;
                                    /** Format: date-time */
                                    addedAt: string;
                                    addedPrice: number | null;
                                    quote: {
                                        symbol: string;
                                        price: number;
                                        previousClose: number;
                                        open: number | null;
                                        dayHigh: number | null;
                                        dayLow: number | null;
                                        volume: number | null;
                                        averageVolume: number | null;
                                        change: number;
                                        changePct: number;
                                        fiftyTwoWeekHigh: number | null;
                                        fiftyTwoWeekLow: number | null;
                                        freshness: {
                                            /** Format: date-time */
                                            asOf: string;
                                            delayedMinutes: number;
                                            stale: boolean;
                                            source: string;
                                        };
                                    } | null;
                                    sparkline: number[];
                                }[];
                                lastSeenAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    watchlistId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    watchlistId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            watchlist: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                position: number;
                                items: {
                                    /** Format: uuid */
                                    id: string;
                                    symbol: string;
                                    instrument: {
                                        symbol: string;
                                        name: string;
                                        /** @enum {string} */
                                        exchange: "NSE" | "BSE";
                                        sector: string | null;
                                    };
                                    thesis: ({
                                        /** @enum {string} */
                                        kind: "target_price";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "breakout_above";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "through_results";
                                    } | {
                                        /** @enum {string} */
                                        kind: "curious";
                                    }) | null;
                                    /** Format: date-time */
                                    addedAt: string;
                                    addedPrice: number | null;
                                    quote: {
                                        symbol: string;
                                        price: number;
                                        previousClose: number;
                                        open: number | null;
                                        dayHigh: number | null;
                                        dayLow: number | null;
                                        volume: number | null;
                                        averageVolume: number | null;
                                        change: number;
                                        changePct: number;
                                        fiftyTwoWeekHigh: number | null;
                                        fiftyTwoWeekLow: number | null;
                                        freshness: {
                                            /** Format: date-time */
                                            asOf: string;
                                            delayedMinutes: number;
                                            stale: boolean;
                                            source: string;
                                        };
                                    } | null;
                                    sparkline: number[];
                                }[];
                                lastSeenAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/watchlists/{watchlistId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    watchlistId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        symbol: string;
                        /** @default null */
                        thesis?: ({
                            /** @enum {string} */
                            kind: "target_price";
                            price: number;
                        } | {
                            /** @enum {string} */
                            kind: "breakout_above";
                            price: number;
                        } | {
                            /** @enum {string} */
                            kind: "through_results";
                        } | {
                            /** @enum {string} */
                            kind: "curious";
                        }) | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            watchlist: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                position: number;
                                items: {
                                    /** Format: uuid */
                                    id: string;
                                    symbol: string;
                                    instrument: {
                                        symbol: string;
                                        name: string;
                                        /** @enum {string} */
                                        exchange: "NSE" | "BSE";
                                        sector: string | null;
                                    };
                                    thesis: ({
                                        /** @enum {string} */
                                        kind: "target_price";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "breakout_above";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "through_results";
                                    } | {
                                        /** @enum {string} */
                                        kind: "curious";
                                    }) | null;
                                    /** Format: date-time */
                                    addedAt: string;
                                    addedPrice: number | null;
                                    quote: {
                                        symbol: string;
                                        price: number;
                                        previousClose: number;
                                        open: number | null;
                                        dayHigh: number | null;
                                        dayLow: number | null;
                                        volume: number | null;
                                        averageVolume: number | null;
                                        change: number;
                                        changePct: number;
                                        fiftyTwoWeekHigh: number | null;
                                        fiftyTwoWeekLow: number | null;
                                        freshness: {
                                            /** Format: date-time */
                                            asOf: string;
                                            delayedMinutes: number;
                                            stale: boolean;
                                            source: string;
                                        };
                                    } | null;
                                    sparkline: number[];
                                }[];
                                lastSeenAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlists/{watchlistId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    watchlistId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            watchlist: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                position: number;
                                items: {
                                    /** Format: uuid */
                                    id: string;
                                    symbol: string;
                                    instrument: {
                                        symbol: string;
                                        name: string;
                                        /** @enum {string} */
                                        exchange: "NSE" | "BSE";
                                        sector: string | null;
                                    };
                                    thesis: ({
                                        /** @enum {string} */
                                        kind: "target_price";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "breakout_above";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "through_results";
                                    } | {
                                        /** @enum {string} */
                                        kind: "curious";
                                    }) | null;
                                    /** Format: date-time */
                                    addedAt: string;
                                    addedPrice: number | null;
                                    quote: {
                                        symbol: string;
                                        price: number;
                                        previousClose: number;
                                        open: number | null;
                                        dayHigh: number | null;
                                        dayLow: number | null;
                                        volume: number | null;
                                        averageVolume: number | null;
                                        change: number;
                                        changePct: number;
                                        fiftyTwoWeekHigh: number | null;
                                        fiftyTwoWeekLow: number | null;
                                        freshness: {
                                            /** Format: date-time */
                                            asOf: string;
                                            delayedMinutes: number;
                                            stale: boolean;
                                            source: string;
                                        };
                                    } | null;
                                    sparkline: number[];
                                }[];
                                lastSeenAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    watchlistId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        thesis: ({
                            /** @enum {string} */
                            kind: "target_price";
                            price: number;
                        } | {
                            /** @enum {string} */
                            kind: "breakout_above";
                            price: number;
                        } | {
                            /** @enum {string} */
                            kind: "through_results";
                        } | {
                            /** @enum {string} */
                            kind: "curious";
                        }) | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            watchlist: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                position: number;
                                items: {
                                    /** Format: uuid */
                                    id: string;
                                    symbol: string;
                                    instrument: {
                                        symbol: string;
                                        name: string;
                                        /** @enum {string} */
                                        exchange: "NSE" | "BSE";
                                        sector: string | null;
                                    };
                                    thesis: ({
                                        /** @enum {string} */
                                        kind: "target_price";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "breakout_above";
                                        price: number;
                                    } | {
                                        /** @enum {string} */
                                        kind: "through_results";
                                    } | {
                                        /** @enum {string} */
                                        kind: "curious";
                                    }) | null;
                                    /** Format: date-time */
                                    addedAt: string;
                                    addedPrice: number | null;
                                    quote: {
                                        symbol: string;
                                        price: number;
                                        previousClose: number;
                                        open: number | null;
                                        dayHigh: number | null;
                                        dayLow: number | null;
                                        volume: number | null;
                                        averageVolume: number | null;
                                        change: number;
                                        changePct: number;
                                        fiftyTwoWeekHigh: number | null;
                                        fiftyTwoWeekLow: number | null;
                                        freshness: {
                                            /** Format: date-time */
                                            asOf: string;
                                            delayedMinutes: number;
                                            stale: boolean;
                                            source: string;
                                        };
                                    } | null;
                                    sparkline: number[];
                                }[];
                                lastSeenAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/watchlists/{watchlistId}/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    since?: string;
                };
                header?: never;
                path: {
                    watchlistId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            digest: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                watchlistId: string;
                                /** Format: date-time */
                                generatedAt: string;
                                since: {
                                    /** Format: date-time */
                                    at: string;
                                    /** @enum {string} */
                                    reason: "checkpoint" | "previous_close" | "first_visit" | "requested";
                                };
                                gap: {
                                    wallMs: number;
                                    sessions: number;
                                    sinceLabel: string;
                                    openLabel: string;
                                };
                                market: {
                                    /** @enum {string} */
                                    phase: "pre_open" | "open" | "post_close" | "closed_weekend" | "closed_holiday";
                                    indexSymbol: string;
                                    indexPct: number;
                                    headline: string;
                                    holidayName: string | null;
                                };
                                verdict: {
                                    /** @enum {string} */
                                    tone: "nothing" | "look" | "triggered";
                                    headline: string;
                                    subline: string;
                                };
                                cards: {
                                    symbol: string;
                                    instrument: {
                                        symbol: string;
                                        name: string;
                                        /** @enum {string} */
                                        exchange: "NSE" | "BSE";
                                        sector: string | null;
                                    };
                                    priceThen: number;
                                    priceNow: number;
                                    move: {
                                        totalPct: number;
                                        marketPct: number;
                                        stockPct: number;
                                        beta: number;
                                        indexSymbol: string;
                                        indexPct: number;
                                    };
                                    volatility: {
                                        dailySigmaPct: number;
                                        moveInSigmas: number;
                                    };
                                    volumeRatio: number | null;
                                    headline: string;
                                    why: string | null;
                                    sources: {
                                        id: string;
                                        /** @enum {string} */
                                        kind: "filing" | "news";
                                        title: string;
                                        url: string;
                                        source: string;
                                        /** Format: date-time */
                                        publishedAt: string;
                                        category: string | null;
                                        sentiment: number | null;
                                    }[];
                                    story: {
                                        id: string;
                                        /** @enum {string} */
                                        kind: "news" | "filing" | "price";
                                        /** Format: date-time */
                                        at: string;
                                        title: string;
                                        detail: string | null;
                                        source: string;
                                        sourceUrl: string | null;
                                        url: string | null;
                                        price: number | null;
                                        dayChangePct: number | null;
                                        /** @enum {string} */
                                        tone: "up" | "down" | "neutral";
                                        weight: number;
                                    }[];
                                    summary: string;
                                    narration: string;
                                    chips: {
                                        label: string;
                                        /** @enum {string} */
                                        tone: "neutral" | "rise" | "fall" | "market" | "iris" | "stale";
                                    }[];
                                    signals: {
                                        /** @enum {string} */
                                        kind: "thesis_target_reached" | "thesis_breakout" | "thesis_results_landed" | "results_upcoming" | "ex_dividend_upcoming" | "week52_high" | "week52_low" | "crossed_added_price" | "round_number_crossed" | "volume_spike" | "unusual_move" | "gap_open";
                                        tier: 1 | 2 | 3 | 4;
                                        at: string | null;
                                        summary: string;
                                        data: {
                                            [key: string]: number | string | boolean;
                                        };
                                    }[];
                                    score: number;
                                    series: {
                                        /** Format: date-time */
                                        t: string;
                                        c: number;
                                    }[];
                                    sinceIndex: number;
                                }[];
                                quiet: {
                                    symbol: string;
                                    name: string;
                                    priceNow: number;
                                    changePct: number;
                                    moveInSigmas: number;
                                    sparkline: number[];
                                    note: {
                                        title: string;
                                        source: string;
                                        sourceUrl: string | null;
                                        url: string;
                                        /** Format: date-time */
                                        at: string;
                                    } | null;
                                }[];
                                unavailable: {
                                    symbol: string;
                                    name: string;
                                }[];
                                script: {
                                    id: string;
                                    /** @enum {string} */
                                    kind: "intro" | "card" | "quiet" | "outro";
                                    symbol: string | null;
                                    text: string;
                                }[];
                                freshness: {
                                    /** Format: date-time */
                                    asOf: string;
                                    delayedMinutes: number;
                                    stale: boolean;
                                    source: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/digest/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cards for a set of symbols over a window. Every symbol that can be priced gets a card; ordering is by how much each change mattered. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        symbols: string[];
                        /** Format: date-time */
                        since: string;
                        /** Format: date-time */
                        until?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            since: string;
                            /** Format: date-time */
                            until: string;
                            /** Format: date-time */
                            generatedAt: string;
                            gap: {
                                wallMs: number;
                                sessions: number;
                                sinceLabel: string;
                                openLabel: string;
                            };
                            market: {
                                /** @enum {string} */
                                phase: "pre_open" | "open" | "post_close" | "closed_weekend" | "closed_holiday";
                                indexSymbol: string;
                                indexPct: number;
                                headline: string;
                                holidayName: string | null;
                            };
                            freshness: {
                                /** Format: date-time */
                                asOf: string;
                                delayedMinutes: number;
                                stale: boolean;
                                source: string;
                            };
                            cards: {
                                symbol: string;
                                instrument: {
                                    symbol: string;
                                    name: string;
                                    /** @enum {string} */
                                    exchange: "NSE" | "BSE";
                                    sector: string | null;
                                };
                                priceThen: number;
                                priceNow: number;
                                move: {
                                    totalPct: number;
                                    marketPct: number;
                                    stockPct: number;
                                    beta: number;
                                    indexSymbol: string;
                                    indexPct: number;
                                };
                                volatility: {
                                    dailySigmaPct: number;
                                    moveInSigmas: number;
                                };
                                volumeRatio: number | null;
                                headline: string;
                                why: string | null;
                                sources: {
                                    id: string;
                                    /** @enum {string} */
                                    kind: "filing" | "news";
                                    title: string;
                                    url: string;
                                    source: string;
                                    /** Format: date-time */
                                    publishedAt: string;
                                    category: string | null;
                                    sentiment: number | null;
                                }[];
                                story: {
                                    id: string;
                                    /** @enum {string} */
                                    kind: "news" | "filing" | "price";
                                    /** Format: date-time */
                                    at: string;
                                    title: string;
                                    detail: string | null;
                                    source: string;
                                    sourceUrl: string | null;
                                    url: string | null;
                                    price: number | null;
                                    dayChangePct: number | null;
                                    /** @enum {string} */
                                    tone: "up" | "down" | "neutral";
                                    weight: number;
                                }[];
                                summary: string;
                                narration: string;
                                chips: {
                                    label: string;
                                    /** @enum {string} */
                                    tone: "neutral" | "rise" | "fall" | "market" | "iris" | "stale";
                                }[];
                                signals: {
                                    /** @enum {string} */
                                    kind: "thesis_target_reached" | "thesis_breakout" | "thesis_results_landed" | "results_upcoming" | "ex_dividend_upcoming" | "week52_high" | "week52_low" | "crossed_added_price" | "round_number_crossed" | "volume_spike" | "unusual_move" | "gap_open";
                                    tier: 1 | 2 | 3 | 4;
                                    at: string | null;
                                    summary: string;
                                    data: {
                                        [key: string]: number | string | boolean;
                                    };
                                }[];
                                score: number;
                                series: {
                                    /** Format: date-time */
                                    t: string;
                                    c: number;
                                }[];
                                sinceIndex: number;
                            }[];
                            unavailable: {
                                symbol: string;
                                name: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlists/{watchlistId}/digest/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    watchlistId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            seenAt: string;
                            snapshotCount: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/speech": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Returns audio/mpeg bytes for one narration segment. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        text: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/stocks/{symbol}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    since?: string;
                };
                header?: never;
                path: {
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            report: {
                                symbol: string;
                                instrument: {
                                    symbol: string;
                                    name: string;
                                    /** @enum {string} */
                                    exchange: "NSE" | "BSE";
                                    sector: string | null;
                                };
                                /** Format: date-time */
                                since: string;
                                /** Format: date-time */
                                generatedAt: string;
                                headline: string;
                                why: string | null;
                                sections: {
                                    title: string;
                                    body: string;
                                }[];
                                numbers: {
                                    label: string;
                                    value: string;
                                }[];
                                sources: {
                                    id: string;
                                    /** @enum {string} */
                                    kind: "filing" | "news";
                                    title: string;
                                    url: string;
                                    source: string;
                                    /** Format: date-time */
                                    publishedAt: string;
                                    category: string | null;
                                    sentiment: number | null;
                                }[];
                                move: {
                                    totalPct: number;
                                    marketPct: number;
                                    stockPct: number;
                                    beta: number;
                                    indexSymbol: string;
                                    indexPct: number;
                                };
                                series: {
                                    /** Format: date-time */
                                    t: string;
                                    c: number;
                                }[];
                                sinceIndex: number;
                                /** @enum {string} */
                                writer: "model" | "template";
                                freshness: {
                                    /** Format: date-time */
                                    asOf: string;
                                    delayedMinutes: number;
                                    stale: boolean;
                                    source: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/stocks/{symbol}/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Filings and news for one stock since an instant. Sources only — the written story lives on the report. */
        get: {
            parameters: {
                query?: {
                    since?: string;
                };
                header?: never;
                path: {
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            symbol: string;
                            /** Format: date-time */
                            since: string;
                            sources: {
                                id: string;
                                /** @enum {string} */
                                kind: "filing" | "news";
                                title: string;
                                url: string;
                                source: string;
                                /** Format: date-time */
                                publishedAt: string;
                                category: string | null;
                                sentiment: number | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/speech/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            enabled: boolean;
                            provider: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/users/{externalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    externalId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @default Investor */
                        name?: string;
                        metadata?: {
                            [key: string]: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                externalId: string;
                                /** Format: uuid */
                                userId: string;
                                /** Format: uuid */
                                watchlistId: string;
                                name: string;
                                metadata: {
                                    [key: string]: string;
                                };
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/users/{externalId}/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    externalId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        items: {
                            symbol: string;
                            /** @default null */
                            thesis?: ({
                                /** @enum {string} */
                                kind: "target_price";
                                price: number;
                            } | {
                                /** @enum {string} */
                                kind: "breakout_above";
                                price: number;
                            } | {
                                /** @enum {string} */
                                kind: "through_results";
                            } | {
                                /** @enum {string} */
                                kind: "curious";
                            }) | null;
                            /** Format: date-time */
                            addedAt?: string;
                            addedPrice?: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            watchlistId: string;
                            itemCount: number;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/users/{externalId}/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    since?: string;
                };
                header?: never;
                path: {
                    externalId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            digest: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                watchlistId: string;
                                /** Format: date-time */
                                generatedAt: string;
                                since: {
                                    /** Format: date-time */
                                    at: string;
                                    /** @enum {string} */
                                    reason: "checkpoint" | "previous_close" | "first_visit" | "requested";
                                };
                                gap: {
                                    wallMs: number;
                                    sessions: number;
                                    sinceLabel: string;
                                    openLabel: string;
                                };
                                market: {
                                    /** @enum {string} */
                                    phase: "pre_open" | "open" | "post_close" | "closed_weekend" | "closed_holiday";
                                    indexSymbol: string;
                                    indexPct: number;
                                    headline: string;
                                    holidayName: string | null;
                                };
                                verdict: {
                                    /** @enum {string} */
                                    tone: "nothing" | "look" | "triggered";
                                    headline: string;
                                    subline: string;
                                };
                                cards: {
                                    symbol: string;
                                    instrument: {
                                        symbol: string;
                                        name: string;
                                        /** @enum {string} */
                                        exchange: "NSE" | "BSE";
                                        sector: string | null;
                                    };
                                    priceThen: number;
                                    priceNow: number;
                                    move: {
                                        totalPct: number;
                                        marketPct: number;
                                        stockPct: number;
                                        beta: number;
                                        indexSymbol: string;
                                        indexPct: number;
                                    };
                                    volatility: {
                                        dailySigmaPct: number;
                                        moveInSigmas: number;
                                    };
                                    volumeRatio: number | null;
                                    headline: string;
                                    why: string | null;
                                    sources: {
                                        id: string;
                                        /** @enum {string} */
                                        kind: "filing" | "news";
                                        title: string;
                                        url: string;
                                        source: string;
                                        /** Format: date-time */
                                        publishedAt: string;
                                        category: string | null;
                                        sentiment: number | null;
                                    }[];
                                    story: {
                                        id: string;
                                        /** @enum {string} */
                                        kind: "news" | "filing" | "price";
                                        /** Format: date-time */
                                        at: string;
                                        title: string;
                                        detail: string | null;
                                        source: string;
                                        sourceUrl: string | null;
                                        url: string | null;
                                        price: number | null;
                                        dayChangePct: number | null;
                                        /** @enum {string} */
                                        tone: "up" | "down" | "neutral";
                                        weight: number;
                                    }[];
                                    summary: string;
                                    narration: string;
                                    chips: {
                                        label: string;
                                        /** @enum {string} */
                                        tone: "neutral" | "rise" | "fall" | "market" | "iris" | "stale";
                                    }[];
                                    signals: {
                                        /** @enum {string} */
                                        kind: "thesis_target_reached" | "thesis_breakout" | "thesis_results_landed" | "results_upcoming" | "ex_dividend_upcoming" | "week52_high" | "week52_low" | "crossed_added_price" | "round_number_crossed" | "volume_spike" | "unusual_move" | "gap_open";
                                        tier: 1 | 2 | 3 | 4;
                                        at: string | null;
                                        summary: string;
                                        data: {
                                            [key: string]: number | string | boolean;
                                        };
                                    }[];
                                    score: number;
                                    series: {
                                        /** Format: date-time */
                                        t: string;
                                        c: number;
                                    }[];
                                    sinceIndex: number;
                                }[];
                                quiet: {
                                    symbol: string;
                                    name: string;
                                    priceNow: number;
                                    changePct: number;
                                    moveInSigmas: number;
                                    sparkline: number[];
                                    note: {
                                        title: string;
                                        source: string;
                                        sourceUrl: string | null;
                                        url: string;
                                        /** Format: date-time */
                                        at: string;
                                    } | null;
                                }[];
                                unavailable: {
                                    symbol: string;
                                    name: string;
                                }[];
                                script: {
                                    id: string;
                                    /** @enum {string} */
                                    kind: "intro" | "card" | "quiet" | "outro";
                                    symbol: string | null;
                                    text: string;
                                }[];
                                freshness: {
                                    /** Format: date-time */
                                    asOf: string;
                                    delayedMinutes: number;
                                    stale: boolean;
                                    source: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/users/{externalId}/digest/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    externalId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date-time */
                        seenAt?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            seenAt: string;
                            snapshotCount: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
